#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=8g,walltime=0:05:00
#PBS -N app-tcks2tractmasks
#PBS -V

# Extract fields from config.json

tcks=$(jq -r .tcks config.json)
mask=$(jq -r .fa config.json)

#### tractmasks analysis
output_dir=./tractmasks
[ -d ${output_dir} ] || { mkdir ${output_dir}; }
singularity exec -e docker://brainlife/dipy:1.4.1 bash ./scripts/convert_trk_to_nii.sh ${tcks} ${mask} ${output_dir}

echo "all done"